import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import ibgeService from './../services/ibgeService';
import Autocomplete from 'react-autocomplete';
import router, { useRouter } from 'next/router';

interface Municipio {
  id: number;
  nome: string;
}

const Home: NextPage = () => {
  const [municipios, setMunicipios] = useState<Municipio[]>([]);
  const [municipioSelecionado, setMunicipioSelecionado] = useState('');

  useEffect(() => {
    const fetchMunicipios = async () => {
      const res = await ibgeService.getMunicipios();
      console.log(res);
      setMunicipios(res);
    };

    fetchMunicipios();
  }, []);

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen bg-gray-100">
        <h1>Covid</h1>

        <Autocomplete
          getItemValue={(municipio: Municipio) => municipio.nome}
          items={municipios.filter((municipio) =>
            municipio.nome
              .toLowerCase()
              .includes(municipioSelecionado.toLowerCase())
          )}
          renderItem={(municipio: Municipio, isHighlighted: Boolean) => (
            <div
              style={{ background: isHighlighted ? 'lightgray' : 'white' }}
              key={municipio.id}
            >
              {municipio.nome}
            </div>
          )}
          value={municipioSelecionado}
          onChange={(e: any) => setMunicipioSelecionado(e.target.value)}
          onSelect={(val: string) => {
            setMunicipioSelecionado(val);
            router.push(val);
          }}
        />
      </div>
    </div>
  );
};

export default Home;
